[package]
name = "memes-tracker-fetching"
version = "0.1.0"
authors = ["Dmitry Shur <dimashur@gmail.com>"]

[dependencies]
actix = "0.5.5"
actix-web = "0.4.10"
reqwest = "0.8.5"
select = "0.4.2"
regex = "0.2.10"
